INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H1', '할머니 손칼국수', 5000, 'G1', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H2', '혜화칼국수', 7000, 'G1', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H3', '황생가 칼국수', 8000, 'G1', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H4', '연백', 6000, 'G1', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H5', '대장장이 화덕피자', 16000, 'G2', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H6', '삼청동 화덕피자', 15000, 'G2', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H7', '계동피자', 15000, 'G2', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H8', '산내리 북촌점', 14000, 'G3', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H9', '삼청화', 8000, 'G3', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H10', '한가네불고기', 10000, 'G3', 'B1');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H11', '키이로메시야', 6000, 'G4', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H12', '카레팩토리', 7500, 'G4', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H13', '델리커리', 8500, 'G4', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H14', '샛집남원 추어탕', 9000, 'G5', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H15', '춘향골 남원 추어탕', 6000, 'G5', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H16', '본가', 11000, 'G6', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H17', '소담골', 14000, 'G6', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H18', '호박식당', 10000, 'G6', 'B2');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H19', '병천 본가순대', 6000, 'G7','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H20', '명가현모 병천순대', 7000, 'G7','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H21', '먹거리 순대', 6000, 'G7','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H22', '충남집아우내 한방순대', 5000, 'G7','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H23', '병천 본가순대', 15000, 'G8','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H24', '명가현모 병천순대', 17000, 'G8','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H25', '먹거리 순대', 17000, 'G8','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H26', '충남집아우내 한방순대', 18000, 'G8','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H27', '아우내 엄나무 순대', 19000, 'G9','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H28', '병천 본가순대', 18000, 'G9','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H29', '은행나무집', 18000, 'G9','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H30', '고향산장', 20000, 'G9','B3');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H31', '테딘', 10000, 'G10','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H32', '테딘', 11000, 'G11','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H33', '테딘', 8000, 'G12','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H34', '테딘', 4000, 'G13','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H35', '테딘', 3000, 'G14','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H36', '테딘', 6000, 'G15','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H37', '테딘', 8000, 'G16','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H38', '테딘', 9000, 'G17','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H39', '테딘', 10000, 'G18','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H40', '테딘', 9000, 'G19','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H41', '테딘', 4000, 'G20','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H42', '테딘', 8000, 'G21','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H43', '테딘', 8000, 'G22','B4');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H44', '형제전통 돼지국밥', 5000, 'G23','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H45', '쌍둥이 돼지국밥', 6000, 'G23','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H46', '밀양순대돼지국밥', 6500, 'G23','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H47', '선창횟집', 30000, 'G24','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H48', '막썰어파는 횟집', 30000, 'G24','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H49', '할매횟집', 55000, 'G24','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H50', '라마앤바나나', 14000, 'G25','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H51', '판자브인도요리전문점', 15000, 'G25','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H52', '꼬치', 14000, 'G25','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H53', '한양 족발', 30000, 'G26','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H54', '한성 족발', 23000, 'G26','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H55', '동래 불족발', 20000, 'G26','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H56', '승기 씨앗호떡', 1000, 'G27','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H57', '승윤 씨앗호떡', 1000, 'G27','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H58', '아저씨 씨앗호떡', 1000, 'G27','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H59', '소문난 돼지국밥', 6000, 'G28','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H60', '옥천돼지국밥', 6500, 'G28','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H61', '강남돼지국밥', 6000, 'G28','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H62', '해변집', 40000, 'G29','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H63', '왔다! 해녀집', 50000, 'G29','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H64', '오륙도', 40000, 'G29','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H65', '태종대 짬뽕', 40000, 'G30','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H66', '차이난 짬뽕', 40000, 'G30','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H67', '홍콩반점', 40000, 'G30','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H68', '한월식당', 10000, 'G31','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H69', '자갈치즉석 생선구이', 13000, 'G31','B5');
INSERT INTO Restaurant (restaurant_id, restaurant_name, food_fee, food_id, sight_id) VALUES ('H70', '부산 생선구이', 11000, 'G31','B5');