INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F1', '호텔썬비', '더블룸 - 주중/주말', 100000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F2', '호텔썬비', '트윈룸 - 주중/주말', 120000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F3', '호텔썬비', '온돌룸 - 주중/주말', 140000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F4', '고궁호텔', '더블 - 주중/주말', 68000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F5', '고궁호텔', '트윈 - 주중/주말', 68000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F6', '고궁호텔', '디럭스트윈 - 주중/주말', 78000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F7', '고궁호텔', '특식- 주중/주말', 98000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F8', '호텔 통', '더블 - 주중/주말', 80000, E1, 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F9', '호텔 통', '트윈 - 주중/주말', 80000, E1, 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F10', '호텔 통', '트리플 - 주중/주말', 10000, 'E1', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F11', '카라모텔', '더블 - 주중', 35000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F12', '카라모텔', '더블 - 주말', 55000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F13', '카라모텔', '디럭스 더블 - 주중', 52000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F14', '카라모텔', '디럭스 더블 - 주말', 65000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F15', '카라모텔', '트윈 - 주중', 60000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F16', '카라모텔', '트윈 - 주말', 75000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F17', '아미가 인 서울', '디럭스트윈 - 주중/주말', 80000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F18', '아미가 인 서울', '트윈 - 주중/주말', 60000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F19', '아미가 인 서울', '클래식모던 - 주중/주말', 45000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F20', '수송모텔', '일반침대 - 주중/주말', 60000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F21', '수송모텔', '한실 - 주중/주말', 70000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F22', '수송모텔', '트윈룸 - 주중/주말', 70000, 'E2', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F23', '애플백팩커스', '싱글 - 주중/주말', 38000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F24', '애플백팩커스', '더블 - 주중/주말', 53000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F25', '애플백팩커스', '트리플 - 주중/주말', 68000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F26', '애플백팩커스', '패밀리 - 주중/주말', 83000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F27', '라임스테이', '더블 - 주중', 50000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F28', '라임스테이', '더블 - 주말', 55000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F29', '라임스테이', '트윈 - 주중', 55000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F30', '라임스테이', '트윈 - 주말', 60000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F31', '라임스테이', '트리플 - 주중', 75000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F32', '라임스테이', '트리플 - 주말', 80000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F33', '임스하우스', '싱글 - 주중/주말', 40000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F34', '임스하우스', '더블 - 주중/주말', 50000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F35', '임스하우스', '트윈 - 주중/주말', 55000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F36', '임스하우스', '트리플 - 주중/주말', 65000, 'E3', 'B1');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F37', '파로스 관광호텔', '스탠다드 트윈 - 주중', 88000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F38', '파로스 관광호텔', '스탠다드 투윈 - 주말', 109000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F39', '파로스 관광호텔', '스탠다드 더블 - 주중', 88000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F40', '파로스 관광호텔', '스탠다드 더블 - 주말', 109000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F41', '파로스 관광호텔', '모던 스탠다드 - 주중', 99000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F42', '파로스 관광호텔', '모던 스탠다드 - 주말', 120000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F43', '파로스 관광호텔', '모던 디럭스 - 주중', 110000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F44', '파로스 관광호텔', '모던 디럭스 - 주말', 130000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F45', '파로스 관광호텔', '클래식 디럭스 - 주중', 110000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F46', '파로스 관광호텔', '클래식 디럭스 - 주말', 130000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F47', '파로스 관광호텔', '스위트 - 주중', 450000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F48', '파로스 관광호텔', '스위트 - 주말', 600000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F49', '다비드 호텔', '더블베드룸 - 주중', 65000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F50', '다비드 호텔', '더블베드룸 - 주말', 75000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F51', '다비드 호텔', '트윈베드룸 - 주중', 75000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F52', '다비드 호텔', '트윈베드룸 - 주말', 85000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F53', '다비드 호텔', '트리플베드룸 - 주중', 85000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F54', '다비드 호텔', '트리플베드룸 - 주말', 95000, 'E4', 'B2');-
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F55', '다비드 호텔', '패밀리룸 - 주중', 95000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F56', '다비드 호텔', '패밀리룸 - 주말', 105000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F57', '잠실관광호텔', '이코노미 싱글- 주중/주말', 72000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F58', '잠실관광호텔', '패밀리 트윈 - 주중/주말', 115000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F59', '잠실관광호텔', '스탠다드 더블- 주중/주말', 105000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F60', '잠실관광호텔', '스탠다드 트윈- 주중/주말', 105000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F61', '잠실관광호텔', '온돌 - 주중/주말', 105000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F62', '잠실관광호텔', '비즈니스 더블 - 주중/주말', 115000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F63', '잠실관광호텔', '디럭스 더블 - 주중/주말', 135000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F64', '잠실관광호텔', '잠실 스위트- 주중/주말', 250000, 'E4', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F65', '스카이 모텔', '일반실- 주중', 45000, 'E5', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F66', '스카이 모텔', '일반실- 주말', 55000, 'E5', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F67', '카프리 모텔', '일반실- 주중', 50000, 'E5', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F68', '카프리 모텔', '일반실- 주말', 60000, 'E5', 'B2');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F69', '상록호텔', '싱글룸 - 주중/주말', 85000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F70', '상록호텔', '더블룸 - 주중/주말', 95000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F71', '상록호텔', '스위트룸 - 주중/주말', 115000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F72', '호텔 로터스', '더블 - 주중', 85000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F73', '호텔 로터스', '더블 - 주말', 110000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F74', '호텔 로터스', '디럭스 - 주중', 75000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F75', '호텔 로터스', '디럭스 - 주말', 100000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F76', '호텔 로터스', '트리플 - 주중', 130000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F77', '호텔 로터스', '트리플 - 주말', 110000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F78', '샹글리에', '더블', 70000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F79', '샹글리에', '트윈', 80000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F80', '샹글리에', '트리플', 90000, 'E6', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F81', '무지개무인텔', '일반실 - 주중', 40000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F82', '무지개무인텔', '일반실 - 주말', 50000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F83', '무지개무인텔', '특실 - 주중', 50000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F84', '무지개무인텔', '특실 - 주말', 55000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F85', '프라임', '일반실 - 주중', 40000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F86', '프라임', '일반실 - 주말', 50000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F87', '프라임', '특실(커플pc) - 주중', 50000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F88', '프라임', '특실(커플pc) - 주말', 60000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F89', '에이스', '공통객실 - 주중', 30000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F90', '에이스', '공통객실 - 주말', 40000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F91', 'JS', '공통객실 - 주중', 30000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F92', 'JS', '공통객실 - 주말', 35000, 'E7', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F93', '영남여인숙', '일반', 15000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F94', '영남여인숙', '특', 25000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F95', '아우네여인숙', '일반', 20000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F96', '창녕여인숙', '일반', 15000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F97', '동남여인숙', '주중', 20000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F98', '동남여인숙', '주말', 25000, 'E8', 'B3');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F99', '테딘 리조트', '골드 - 회원본인/비수기/주중', 50000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F100', '테딘 리조트', '골드 - 회원본인/비수기/주말', 60000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F101', '테딘 리조트', '골드 - 회원본인/성수기', 60000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F102', '테딘 리조트', '골드 - 법인회원/비수기/주중', 52000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F103', '테딘 리조트', '골드 - 법인회원/비수기/주말', 62000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F104', '테딘 리조트', '골드 - 법인회원/성수기', 62000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F105', '테딘 리조트', '골드 - 회원대여/비수기/주중', 74000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F106', '테딘 리조트', '골드 - 회원대여/비수기/주말', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F107', '테딘 리조트', '골드 - 회원대여/성수기', 127000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F108', '테딘 리조트', '골드 - 일반', 313000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F109', '테딘 리조트', '플래티넘 - 회원본인/비수기/주중', 50000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F110', '테딘 리조트', '플래티넘 - 회원본인/비수기/주말', 60000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F111', '테딘 리조트', '플래티넘 - 회원본인/성수기', 60000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F112', '테딘 리조트', '플래티넘 - 법인회원/비수기/주중', 52000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F113', '테딘 리조트', '플래티넘 - 법인회원/비수기/주말', ,62000 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F114', '테딘 리조트', '플래티넘 - 법인회원/성수기', 62000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F115', '테딘 리조트', '플래티넘 - 회원대여/비수기/주중', 73000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F116', '테딘 리조트', '플래티넘 - 회원대여/비수기/주말', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F117', '테딘 리조트', '플래티넘 - 회원대여/성수기', 127000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F118', '테딘 리조트', '플래티넘 - 일반', 313000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F119', '테딘 리조트', '다이아몬드 40PY - 회원본인/비수기/주중', 80000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F120', '테딘 리조트', '다이아몬드 40PY - 회원본인/비수기/주말', 91000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F121', '테딘 리조트', '다이아몬드 40PY - 회원본인/성수기', 91000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F122', '테딘 리조트', '다이아몬드 40PY - 법인회원/비수기/주중', 82000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F123', '테딘 리조트', '다이아몬드 40PY - 법인회원/비수기/주말', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F124', '테딘 리조트', '다이아몬드 40PY - 법인회원/성수기', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F125', '테딘 리조트', '다이아몬드 40PY - 회원대여/비수기/주중', 124000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F126', '테딘 리조트', '다이아몬드 40PY - 회원대여/비수기/주말', 155000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F127', '테딘 리조트', '다이아몬드 40PY - 회원대여/성수기', 177000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F128', '테딘 리조트', '다이아몬드 40PY - 일반', 480000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F129', '테딘 리조트', '다이아몬드 40PY - 회원본인/비수기/주중', 91000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F130', '테딘 리조트', '다이아몬드 40PY - 회원본인/비수기/주말', 105000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F131', '테딘 리조트', '다이아몬드 40PY - 회원본인/성수기', 105000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F132', '테딘 리조트', '다이아몬드 40PY - 법인회원/비수기/주중', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F133', '테딘 리조트', '다이아몬드 40PY - 법인회원/비수기/주말', 107000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F134', '테딘 리조트', '다이아몬드 40PY - 법인회원/성수기', 107000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F135', '테딘 리조트', '다이아몬드 40PY - 회원대여/비수기/주중', 139000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F136', '테딘 리조트', '다이아몬드 40PY - 회원대여/비수기/주말', 176000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F137', '테딘 리조트', '다이아몬드 40PY - 회원대여/성수기', 201000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F138', '테딘 리조트', '다이아몬드 40PY - 일반', 552000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F139', '테딘 리조트', '포시즌1 - 회원본인/비수기/주중', 91000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F140', '테딘 리조트', '포시즌1 - 회원본인/비수기/주말', 105000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F141', '테딘 리조트', '포시즌1 - 회원본인/성수기', 105000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F142', '테딘 리조트', '포시즌1 - 법인회원/비수기/주중', 93000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F143', '테딘 리조트', '포시즌1 - 법인회원/비수기/주말', 107000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F144', '테딘 리조트', '포시즌1 - 법인회원/성수기', 107000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F145', '테딘 리조트', '포시즌1 - 회원대여/비수기/주중', 139000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F146', '테딘 리조트', '포시즌1 - 회원대여/비수기/주말', 176000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F147', '테딘 리조트', '포시즌1 - 회원대여/성수기', 201000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F148', '테딘 리조트', '포시즌1 - 일반', 552000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F149', '테딘 리조트', '포시즌2 - 회원본인/비수기/주중', 144000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F150', '테딘 리조트', '포시즌2 - 회원본인/비수기/주말', 170000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F151', '테딘 리조트', '포시즌2 - 회원본인/성수기', 170000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F152', '테딘 리조트', '포시즌2 - 법인회원/비수기/주중', 144000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F153', '테딘 리조트', '포시즌2 - 법인회원/비수기/주말', 170000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F154', '테딘 리조트', '포시즌2 - 법인회원/성수기', 170000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F155', '테딘 리조트', '포시즌2 - 회원대여/비수기/주중', 242000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F156', '테딘 리조트', '포시즌2 - 회원대여/비수기/주말', 312000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F157', '테딘 리조트', '포시즌2 - 회원대여/성수기', 324000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F158', '테딘 리조트', '포시즌2 - 일반', 1020000, 'E9', 'B4');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F159', '그랜드호텔', '디럭스 더블 시티뷰 - 주중 ', 180000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F160', '그랜드호텔', '디럭스  더블 시티뷰 - 주말', 204000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F161', '그랜드호텔', '디럭스 트윈 시티뷰 - 주중', 180000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F162', '그랜드호텔', '디럭스 트윈 시티뷰 - 주말', 204000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F163', '그랜드호텔', '디럭스 트윈 씨뷰 - 주중', 213000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F164', '그랜드호텔', '디럭스 트윈 씨뷰 - 주말', 238000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F165', '그랜드호텔', '패밀리 스위트 - 주중', 492000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F166', '그랜드호텔', '패밀리 스위트 - 주말', 524000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F167', '웨스틴 조선 호텔', '디럭스 마운틴뷰- 주중/주말', 310000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F168', '웨스틴 조선 호텔', '디럭스 씨뷰 - 주중/주말', 360000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F169', '웨스틴 조선 호텔', '이그제큐티브 가든뷰 - 주중/주말', 410000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F170', '웨스틴 조선 호텔', '이그제큐티브 씨뷰뷰 - 주중/주말', 440000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F171', '파라다이스 호텔', '스탠다드 더블/트윈 - 주중', 225000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F172', '파라다이스 호텔', '스탠다드 더블/트윈 - 주말', 320000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F173', '파라다이스 호텔', '디럭스 더블베드 - 주중', 243000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F174', '파라다이스 호텔', '디럭스 더블베드 - 주말', 340000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F175', '파라다이스 호텔', '디럭스 더블/트윈 - 주중', 300000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F176', '파라다이스 호텔', '디럭스 더블/트윈 - 주말', 370000, 'E10', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F177', '전망좋은 모텔', 'VIP 실 - 주중(비수기)', 60000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F178', '전망좋은 모텔', 'VIP실 - 주말(비수기)', 80000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F179', '전망좋은 모텔', '특실 - 주중(비수기)', 50000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F180', '전망좋은 모텔', '특실 - 주말(비수기)', 70000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F181', '전망좋은 모텔', '일반실 - 주중(비수기)', 40000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F182', '전망좋은 모텔', '일반실 - 주말(비수기)', 50000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F183', '해운대 비치 모텔', '일반실 - 주중(비수기)', 35000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F184', '해운대 비치 모텔', '일반실 - 주말(비수기)', 50000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F185', '해운대 비치 모텔', '특별실 - 주중(비수기)', 45000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F186', '해운대 비치 모텔', '특별실 - 주말(비수기)', 60000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F187', '싼타페 모텔', '특실 - 주중(비수기)', 45000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F188', '싼타페 모텔', '특실 - 주말(비수기)', 70000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F189', '싼타페 모텔', '한실 - 주중(비수기)', 40000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F190', '싼타페 모텔', '한실 - 주말(비수기)', 60000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F191', '싼타페 모텔', '트윈실 - 주중(비수기)', 50000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F192', '싼타페 모텔', '트윈실 - 주말(비수기)', 80000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F193', '싼타페 모텔', '일반실 - 주중(비수기)', 40000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F194', '싼타페 모텔', '일반실 - 주말(비수기)', 60000, 'E11', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F195', '인디 게스트하우스', '더블 - 주중(비수기)', 60000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F196', '인디 게스트하우스', '더블 - 주말(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F197', '인디 게스트하우스', '트윈 - 주중(비수기)', 60000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F198', '인디 게스트하우스', '트윈 - 주말(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F199', '인디 게스트하우스', '스탠다드 - 주중(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F200', '인디 게스트하우스', '스탠다드 - 주말(비수기)', 90000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F201', '인디 게스트하우스', '4인실 도미토리 - 주중(비수기)', 25000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F202', '인디 게스트하우스', '4인실 도미토리 - 주말(비수기)', 27000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F203', '인디 게스트하우스', '6인실 도미토리 - 주중(비수기)', 23000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F204', '인디 게스트하우스', '6인실 도미토리 - 주말(비수기)', 25000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F205', '스토리 게스트하우스', '2인실 - 주중/주말(비수기)', 70000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F206', '스토리 게스트하우스', '2인실 - 주중/주말(성수기)', 100000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F207', '스토리 게스트하우스', '4인실 - 주중/주말(비수기)', 30000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F208', '스토리 게스트하우스', '4인실 - 주중/주말(성수기)', 35000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F209', '스토리 게스트하우스', '6인실 - 주중/주말(비수기)', 27000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F210', '스토리 게스트하우스', '6인실 - 주중/주말(성수기)', 32000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F211', '스토리 게스트하우스', '8인실 - 주중/주말(비수기)', 25000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F212', '스토리 게스트하우스', '8인실 - 주중/주말(성수기)', 30000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F213', ' 와우 게스트하우스', '커플룸 - 주중/주말(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F214', ' 와우 게스트하우스', '커플룸 - 주중/주말(성수기)', 100000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F215', ' 와우 게스트하우스', '트윈룸 - 주중/주말(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F216', ' 와우 게스트하우스', '트윈룸 - 주중/주말(성수기)', 100000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F217', ' 와우 게스트하우스', '온돌룸 - 주중/주말(비수기)', 80000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F218', ' 와우 게스트하우스', '온돌룸 - 주중/주말(성수기)', 100000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F219', ' 와우 게스트하우스', '4인 도미토리 - 주중/주말(비수기)', 30000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F220', ' 와우 게스트하우스', '4인 도미토리- 주중/주말(성수기)', 35000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F221', ' 와우 게스트하우스', '6인 도미토리 - 주중/주말(비수기)', 28000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F222', ' 와우 게스트하우스', '6인 도미토리- 주중/주말(성수기)', 33000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F223', ' 와우 게스트하우스', '8인 도미토리 - 주중/주말(비수기)', 25000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F224', ' 와우 게스트하우스', '8인 도미토리- 주중/주말(성수기)', 30000, 'E12', 'B5');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F225', '호텔노아 부산', '싱글(온돌/일반) - 주중', 52000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F226', '호텔노아 부산', '싱글(온돌/일반) - 주말', 60000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F227', '호텔노아 부산', '스탠다드(더블/트윈/온돌) - 주중', 80000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F228', '호텔노아 부산', '스탠다드(더블/트윈/온돌) - 주말', 96000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F229', '호텔노아 부산', '패밀리트윈A(온돌/패밀리트윈) - 주중', 107000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F230', '호텔노아 부산', '패밀리트윈A(온돌/패밀리트윈) - 주말', 130000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F231', '호텔노아 부산', '스위트 - 주중', 120000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F232', '호텔노아 부산', '스위트 - 주말', 140000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F233', '호텔노아 부산', '로얄스위트 - 주중', 200000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F234', '호텔노아 부산', '로얄스위트 - 주말', 240000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F235', '피닉스호텔', '더블 - 주중/주말', 105000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F236', '피닉스호텔', '트윈 - 주중/주말', 105000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F237', '피닉스호텔', '스위트 - 주중/주말', 200000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F238', '피닉스호텔', '한실 - 주중/주말', 105000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F239', '이코노미 호텔', '싱글 - 주중', 60000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F240', '이코노미 호텔', '실글 - 주말', 80000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F241', '이코노미 호텔', '트윈 - 주중', 80000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F242', '이코노미 호텔', '트윈 - 주말', 100000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F243', '이코노미 호텔', '트리플 - 주중', 90000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F244', '이코노미 호텔', '트리플 - 주말', 110000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F245', '이코노미 호텔', '더블 - 주중', 70000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F246', '이코노미 호텔', '더블 - 주말', 90000, 'E13', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F247', '아이 모텔', '일반실 - 주중', 44000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F248', '아이 모텔', '일반실 - 주말', 55000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F249', '아이 모텔', '준특실 - 주중', 55000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F250', '아이 모텔', '준특실 - 주말', 66000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F251', '아이 모텔', '특실 - 주중', 66000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F252', '아이 모텔', '특실 - 주말', 77000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F253', '브이모텔', '일반실 - 주중', 60000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F254', '브이모텔', '일반실 - 주말', 80000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F255', '브이모텔', '준특실 - 주중', 80000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F256', '브이모텔', '준특실 - 주말', 100000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F257', '브이모텔', '특실 - 주중', 140000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F258', '브이모텔', '특실 - 주말', 200000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F259', '갤러리 G모텔', '일반실 - 주중', 25000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F260', '갤러리 G모텔', '일반실 - 주말', 30000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F261', '갤러리 G모텔', '준특실 - 주중', 30000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F262', '갤러리 G모텔', '준특실 - 주말', 35000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F263', '갤러리 G모텔', '특실 - 주중', 35000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F264', '갤러리 G모텔', '특실 - 주말', 40000, 'E14', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F265', '애플게스트하우스', '트윈룸 - 주중', 44000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F266', '애플게스트하우스', '트윈룸 - 주말', 48000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F267', '애플게스트하우스', '더블룸 - 주중', 50000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F268', '애플게스트하우스', '더블룸 - 주말', 52000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F269', '애플게스트하우스', '4인 도미토리 - ', 20000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F270', '애플게스트하우스', '4인 도미토리 - ', 22000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F271', '애플게스트하우스', '6인 도미토리 - ', 18000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F272', '애플게스트하우스', '6인 도미토리 - ', 20000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F273', '턴스테이 게스트하우스', '더블룸 - 주중', 55000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F274', '턴스테이 게스트하우스', '더블룸 - 주말', 65000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F275', '턴스테이 게스트하우스', '트리플룸 - 주중', 75000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F276', '턴스테이 게스트하우스', '트리플룸 - 주말', 85000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F277', '턴스테이 게스트하우스', '4인 도미토리 - 주중', 25000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F278', '턴스테이 게스트하우스', '4인 도미토리 - 주말', 28000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F279', '턴스테이 게스트하우스', '6인 도미토리 - 주중', 23000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F280', '턴스테이 게스트하우스', '6인 도미토리 - 주말', 25000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F281', '테라 게스트하우스', '코리아룸 - 주중(6~8인)', 150000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F282', '테라 게스트하우스', '코리아룸 - 주말(6~8인)', 170000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F283', '테라 게스트하우스', '부산룸 - 주중(4~6인)', 120000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F284', '테라 게스트하우스', '부산룸 - 주말(4~6인)', 140000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F285', '테라 게스트하우스', '러브룸 - 주중(2~4인)', 70000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F286', '테라 게스트하우스', '러브룸 - 주말(2~4인)', 90000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F287', '테라 게스트하우스', '해피룸 - 주중(2~4인)', 70000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F288', '테라 게스트하우스', '해피룸 - 주말(2~4인)', 90000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F289', '테라 게스트하우스', '8/10/12 도미토리 (남여공용) - 주중', 25000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F290', '테라 게스트하우스', '8/10/12 도미토리 (남여공용) - 주말', 30000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F291', '테라 게스트하우스', '8/10/12 도미토리 (여성공용) - 주중', 25000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F292', '테라 게스트하우스', '8/10/12 도미토리 (여성공용) - 주말', 30000, 'E15', 'B6');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F293', '비치 모텔', '일반실 - 주중(2인기준)', 50000, 'E16', 'B7');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F294', '비치 모텔', '일반실 - 주말(2인기준)', 60000, 'E16', 'B7');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F295', '청수 모텔', '일반실 - 주중(2인기준)', 50000, 'E16', 'B7');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F296', '청수 모텔', '일반실 - 주말(2인기준)', 60000, 'E16', 'B7');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F297', '태종 파크텔', '일반실 - 주중(2인기준)', 50000, 'E16', 'B7');
INSERT INTO Room (room_id, room_name, room_type, room_fee, stay_id, sight_id) VALUES ('F298', '태종 파크텔', '일반실 - 주말(2인기준)', 60000, 'E16', 'B7');
